# 服务基本信息配置
server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: ai-code-mother
  servlet:
    multipart:
      max-file-size: 10MB # 文件上传最大限制
  profiles:
    active: local
logging:
  level:
    dev:
      langchain4j: DEBUG
--- #启动虚拟线程
spring:
  threads:
    virtual:
      enabled: true

--- # springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.longwingstech.intelligence.longaicodemother.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: false
    username: root
    password: root
--- ############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  token-prefix: Bearer
  # 指定 Cookie 模式下自动填充 token 提交前缀
  cookie-auto-fill-prefix: true
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-128
  # 是否输出操作日志
  is-log: true

--- #部署应用的域名
deploy:
  code_deploy_host: http://localhost